openapi: 3.0.0
info:
  title: XSD Mapper API
  version: 1.0.0
  description: A simple API for demonstrating XSD to XSD mapping.
paths:
  /process-order:
    post:
      summary: Process a customer order
      description: Receives an order in XML format based on the CustomerOrder schema and returns an invoice based on the SalesInvoice schema.
      requestBody:
        description: Customer Order XML
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/CustomerOrder'
      responses:
        '200':
          description: Successful processing
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SalesInvoice'
        '400':
          description: Invalid input
  /orders/{orderId}:
    get:
      summary: Get Order Details
      parameters:
        - name: orderId
          in: path
          required: true
          description: ID of the order to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: An order object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                  status:
                    type: string
                  amount:
                    type: number
        '404':
          description: Order not found.
  /customers/{customerId}:
    get:
      summary: Get Customer Details
      parameters:
        - name: customerId
          in: path
          required: true
          description: ID of the customer to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: A customer object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  customerId:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: Customer not found.
    put:
      summary: Update Customer Details
      parameters:
        - name: customerId
          in: path
          required: true
          description: ID of the customer to update.
          schema:
            type: string
      requestBody:
        description: Customer object with updated fields.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Customer updated successfully.
        '404':
          description: Customer not found.
  /products:
    get:
      summary: List Products
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    productId:
                      type: string
                    name:
                      type: string
                    price:
                      type: number

components:
  schemas:
    CustomerOrder:
      type: object
      xml:
        name: CustomerOrder
      properties:
        OrderID:
          type: string
        CustomerInfo:
          type: object
          properties:
            FirstName:
              type: string
            LastName:
              type: string
            EmailAddress:
              type: string
        ShippingAddress:
          type: object
          properties:
            Street:
              type: string
            City:
              type: string
            PostalCode:
              type: integer
    SalesInvoice:
      type: object
      xml:
        name: SalesInvoice
      properties:
        InvoiceNumber:
          type: string
        BuyerInformation:
          type: object
          properties:
            FullName:
              type: string
            ContactEmail:
              type: string
        DeliveryLocation:
          type: object
          properties:
            AddressLine1:
              type: string
            Town:
              type: string
            Postcode:
              type: string
